CREATE TABLE USERS(
   ID SERIAL PRIMARY KEY,
   CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
   UPDATED_AT TIMESTAMP WITHOUT TIME ZONE,
   PHONE TEXT
);

CREATE TABLE GOODS(
   ID SERIAL PRIMARY KEY,
   CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
   IDENTIFICATION TEXT
);

CREATE TABLE USERS_GOODS(
   ID SERIAL PRIMARY KEY,
   USER_ID INT REFERENCES USERS (ID),
   GOOD_ID INT REFERENCES GOODS (ID)
);

CREATE TABLE SIGNALS(
   ID SERIAL PRIMARY KEY,
   GOOD_ID INT REFERENCES GOODS (ID)
);